In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt

In [2]:
#import the files by uses pandas 
dataset = pd.read_csv("7.1 Social_Network_Ads.csv",header = "infer")

In [3]:
print(dataset)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [4]:
#taking specific data from data set
#ie from all rows:,column[2,3].values
x = dataset.iloc[:,[2,3]].values

In [5]:
#also for purchase y is column 4
y = dataset.iloc[:,4].values

In [6]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [7]:
print(x)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [8]:
#to divide our dataset for training and testing we
#use sklearn
from sklearn.model_selection import train_test_split

In [9]:
#divide into four data sets, can use test_size/traine_size
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.1)

In [10]:
x_train.shape

(360, 2)

In [11]:
x_train

array([[    21,  68000],
       [    24,  32000],
       [    41,  72000],
       [    28,  84000],
       [    35,  91000],
       [    36,  99000],
       [    36,  75000],
       [    45,  79000],
       [    37,  75000],
       [    38,  61000],
       [    35,  47000],
       [    59,  83000],
       [    39, 106000],
       [    26,  52000],
       [    31,  34000],
       [    29,  43000],
       [    37,  33000],
       [    23,  48000],
       [    54,  70000],
       [    26,  17000],
       [    42,  79000],
       [    21,  88000],
       [    35,  73000],
       [    57,  33000],
       [    30,  49000],
       [    26,  43000],
       [    59, 143000],
       [    46,  74000],
       [    29,  83000],
       [    39,  79000],
       [    33, 113000],
       [    39,  96000],
       [    59,  88000],
       [    38,  71000],
       [    59,  76000],
       [    27,  89000],
       [    37,  52000],
       [    36,  54000],
       [    35,  53000],
       [    40,  71000],


In [12]:
y_train

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,

In [13]:
y_train.shape

(360,)

In [14]:
#normalization/convert to one unit
from sklearn.preprocessing import StandardScaler

In [15]:
#make StandardScaler by creating an object
sc = StandardScaler()

In [16]:
#convert x_train to standard scale
x_train = sc.fit_transform(x_train)

In [17]:
#convert x_test to standard scale we only use .transform
x_test = sc.transform(x_test)

In [18]:
x_train

array([[-1.61946121e+00, -6.01738250e-02],
       [-1.33198289e+00, -1.13287365e+00],
       [ 2.97060931e-01,  5.90150443e-02],
       [-9.48678458e-01,  4.16581652e-01],
       [-2.77895710e-01,  6.25162174e-01],
       [-1.82069603e-01,  8.63539912e-01],
       [-1.82069603e-01,  1.48406696e-01],
       [ 6.80365359e-01,  2.67595566e-01],
       [-8.62434962e-02,  1.48406696e-01],
       [ 9.58261069e-03, -2.68754346e-01],
       [-2.77895710e-01, -6.85915389e-01],
       [ 2.02193086e+00,  3.86784435e-01],
       [ 1.05408718e-01,  1.07212043e+00],
       [-1.14033067e+00, -5.36929302e-01],
       [-6.61200138e-01, -1.07327921e+00],
       [-8.52852351e-01, -8.05104258e-01],
       [-8.62434962e-02, -1.10307643e+00],
       [-1.42780899e+00, -6.56118172e-01],
       [ 1.54280032e+00, -5.79390337e-04],
       [-1.14033067e+00, -1.57983191e+00],
       [ 3.92887038e-01,  2.67595566e-01],
       [-1.61946121e+00,  5.35770522e-01],
       [-2.77895710e-01,  8.88122617e-02],
       [ 1.

In [19]:
#now creating a model by KNN we need to import knn
from sklearn.neighbors import KNeighborsClassifier

In [20]:
#specifiy the number of k same as n_neighbors and the metric ie manhattan
#classifier used to build models
#for manhattan p=1 so (n_neighbors = 3, metric = 'manhattan',p=1)
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski')

In [21]:
#create container to fit in the there
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [22]:
#to predict y
y_pred = classifier.predict(x_test)

In [23]:
y_pred

array([0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0])

In [27]:
y_test

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0])

In [24]:
#to get the accuracy of the model
from sklearn.metrics import confusion_matrix

In [25]:
#takes two argments tocompare
cn = confusion_matrix(y_test,y_pred)

In [26]:
cn

array([[25,  2],
       [ 3, 10]])

In [27]:
#test the accuracy
(23+12)/(23+12+1+4)

0.875